import type { TranslationKey } from "@/i18n/translations";

/** A deposit as the UI consumes it. Money is always integer cents. */
export type Deposit = {
  id: string;
  fullName: string;
  phone: string;
  depositCents: number;
  depositDate: string; // YYYY-MM-DD
  durationDays: number;
  dueDate: string; // YYYY-MM-DD (generated by the database)
  grossReturnCents: number; // generated: principal x 1.45
  brokerFeeCents: number; // generated: 10% of the principal (admin's commission)
  netReturnCents: number; // generated: gross - broker fee (what the customer gets)
  profitCents: number; // generated: net - principal (the customer's gain)
  paidAt: string | null; // YYYY-MM-DD
  createdAt: string; // ISO timestamp
};

/** Shape returned by Postgres; mapped to `Deposit` in lib/deposits.ts. */
export type DepositRow = {
  id: string;
  full_name: string;
  phone: string;
  deposit_cents: number;
  deposit_date: string;
  duration_days: number;
  due_date: string;
  gross_return_cents: number;
  broker_fee_cents: number;
  net_return_cents: number;
  profit_cents: number;
  paid_at: string | null;
  created_at: string;
};

/**
 * Server-action outcome. Messages travel as translation keys so the client can
 * render them in the language the user currently has selected.
 */
export type ActionFieldErrors = Record<string, TranslationKey | undefined>;

export type ActionResult =
  | { ok: true; message: TranslationKey }
  | { ok: false; message: TranslationKey; fields?: ActionFieldErrors };
